server {
    listen 80;
    server_name ewvm.epl.di.uminho.pt;

    # 1. Servir o Frontend (Vue 3 compilado)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Importante para o Vue Router se o usares mais tarde
    }

    # 2. Fazer Proxy Reverso das rotas /api para o contentor Node.js
    location /api {
        proxy_pass http://backend:50520; # Usa o nome do serviço do docker-compose
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}